# -*- coding: utf-8 -*-
"""ACTIVITY LAB (09-30-24).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ivSVikau8Bh1973qulhLpqZzHxn9IxQ
"""

!pip install opencv-python

from google.colab import drive
drive.mount('/content/drive')

import cv2
import os

# Function to extract frames
def extract_frames(video_path, output_folder, fps=2):
    # Open the video file
    video_capture = cv2.VideoCapture(video_path)

    # Get the frames per second (fps) of the video
    video_fps = video_capture.get(cv2.CAP_PROP_FPS)

    # Calculate the interval between frames to capture based on video fps and desired fps
    frame_interval = int(video_fps / fps)

    # Create the output folder if it doesn't exist
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    frame_number = 0
    extracted_frame_number = 0

    while True:
        # Read the next frame
        success, frame = video_capture.read()

        # Break the loop when the video ends
        if not success:
            break

        # Save the frame if it's the desired frame (every frame_interval)
        if frame_number % frame_interval == 0:
            frame_filename = os.path.join(output_folder, f"frame_{extracted_frame_number}.jpg")
            cv2.imwrite(frame_filename, frame)
            extracted_frame_number += 1

        frame_number += 1

    # Release the video capture object
    video_capture.release()
    print(f"Extracted {extracted_frame_number} frames to '{output_folder}'.")

# Path to the video file
video_file_path = "/content/drive/MyDrive/videokoto.mov"

# Output folder to save the extracted frames
output_dir = "/content/drive/MyDrive/Yey"

# Extract frames at 2 frames per second
extract_frames(video_file_path, output_dir, fps=2)